# For more information on GitHub Actions' labeler, see https://github.com/actions/labeler

assets:
- assets/**/*

documentation:
- '*.md'

examples:
# Markdown files are reserved for documentation purposes
# YAML files are reserved for Actions and workflows/system
# Nearly any other file format can easily be used as an example/practice file (.html, .txt, .py, etc.)
- examples/**/*

workflow:
- .github/**/*